services:
  frontend:
    container_name: cipherhub_frontend
    build:
      context: .
      target: dev
    restart: always
    command: npm run dockerDev
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
      - /app/.next
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'

  db:
    image: postgres:15-alpine
    restart: always
    container_name: cipherhub_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
